from .generator_prompts import AGENT_SYSTEM_PROMPT as GENERATOR_PROMPT, FOCUSED_SYSTEM_PROMPT as GENERATOR_FOCUSED_PROMPT
from .discriminator_prompts import AGENT_SYSTEM_PROMPT as DISCRIMINATOR_PROMPT, FOCUSED_SYSTEM_PROMPT as DISCRIMINATOR_FOCUSED_PROMPT
from .summarizer_prompts import SUMMARIZER_SYSTEM_PROMPT

__all__ = [
    'GENERATOR_PROMPT',
    'GENERATOR_FOCUSED_PROMPT',
    'DISCRIMINATOR_PROMPT',
    'DISCRIMINATOR_FOCUSED_PROMPT',
    'SUMMARIZER_SYSTEM_PROMPT'
]